# Generated by Django 4.2.5 on 2024-08-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''
        INSERT INTO "public"."users_user" ("password", "last_login", "is_superuser", "id", "email", "name", "is_active", "is_staff", "address", "date_of_birth", "phone_number") VALUES
('pbkdf2_sha256$600000$jMmuYf0S4jkIdPEhUtIJv6$46e49av0WwxOD1asXl3zJ5hPDXsZ46CJHozbuQ7qd1c=', NULL, 't', 'e864b6d9-e053-45e3-8014-1c96adc78ac6', 'mateo@mateo.mateo', '', 't', 't', NULL, NULL, NULL);
        ''')
    ]

